MOUSEKEY_ENABLE     = yes      # Mouse keys
RGBLIGHT_ENABLE     = yes     # Enable WS2812 RGB underlight.
VIA_ENABLE          = yes     # Enable VIA
VIAL_ENABLE         = yes     # Enable VIAL
OLED_ENABLE         = no
OLED_DRIVER         = SSD1306
EXTRAKEY_ENABLE     = yes
LTO_ENABLE          = yes
QMK_SETTINGS        = no
COMBO_ENABLE        = yes
TAP_DANCE_ENABLE = no
AUTO_SHIFT_ENABLE = yes
BACKLIGHT_ENABLE = no
CONSOLE_ENABLE = no
